/**
 * native-crosshair — M15 follow-up: the "native path first" alternative to
 * crosshair-overlay.ts, per the commercial-overlay analysis this follows
 * (2026-08). Writes the four real GoldSrc client cvars
 * (cl_crosshair_color/_size/_translucent, cl_dynamiccrosshair — see
 * native-crosshair-settings.ts) into a small, self-generated leaf cfg
 * (cstrike/16x-crosshair.cfg) and execs it via its own independently-
 * delimited block in cstrike/autoexec.cfg + cstrike/userconfig.cfg.
 *
 * Presented in Settings as the primary/recommended option, with the overlay
 * as the advanced/visual-only alternative, because this one:
 *  - works identically in exclusive fullscreen (it's cvars the engine reads
 *    at its own render time — nothing to do with window compositing, unlike
 *    the overlay's alwaysOnTop game, see crosshair-overlay.ts's Wayland/X11
 *    notes) and on Wayland;
 *  - has zero window/compositor/input-region involvement, so none of the
 *    overlay's platform caveats (or the Electron 43 X11 setIgnoreMouseEvents
 *    regression) apply to it at all;
 *  - is limited to GoldSrc's own real crosshair cvars (color/size/
 *    translucency/dynamic-spread) — no free shape/offset/multi-monitor
 *    control the way the overlay has, since those aren't things the engine's
 *    own crosshair cvars can express.
 *
 * Deliberately independent of content-sync.ts's own managed exec block (a
 * *different* BEGIN/END marker pair, written into the same two target
 * files) rather than folding into content-sync's execPaths/manifest
 * pipeline: this feature toggles independently of any manifest/profile
 * selection and has nothing to do with slots/variants, so piggybacking on
 * that already-incident-prone mechanism (see CLAUDE.md's exec-cycle
 * standing rule) would only add risk for no benefit. Each block owns only
 * the lines between its own markers; content-sync's block and the player's
 * own lines are always left untouched. No cycle-detection pass is needed
 * here (unlike syncManagedExecTargets) because the leaf cfg this module
 * writes is 100% generated by buildNativeCrosshairCfgText — never anything
 * but the four cvar lines above, so it can structurally never contain an
 * `exec` statement that could close a cycle.
 *
 * Only resolveContentPath (path-escape safety) and backupIfNeeded
 * (preserve-on-first-write) are reused from content-sync.ts — both pure
 * path/fs helpers with no manifest/profile/cycle-detection involvement.
 */

import { mkdir, readFile, rename, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { app } from 'electron'
import { getActiveInstall } from './game-install.ts'
import { resolveContentPath, backupIfNeeded } from './content-sync.ts'
import {
  DEFAULT_NATIVE_CROSSHAIR_SETTINGS,
  sanitizeNativeCrosshairSettings,
  buildNativeCrosshairCfgText,
  type NativeCrosshairSettings
} from './native-crosshair-settings.ts'

export type { NativeCrosshairSettings, NativeCrosshairSize } from './native-crosshair-settings.ts'

const FILENAME = 'native-crosshair-settings.json'

const TARGETS = ['cstrike/autoexec.cfg', 'cstrike/userconfig.cfg']
const CFG_RELPATH = 'cstrike/16x-crosshair.cfg'
const CFG_EXEC_NAME = '16x-crosshair.cfg'
const BLOCK_BEGIN = '// === 16X LAUNCHER NATIVE CROSSHAIR — DO NOT EDIT BELOW THIS LINE ==='
const BLOCK_END = '// === 16X LAUNCHER NATIVE CROSSHAIR — END ==='

let settings: NativeCrosshairSettings = { ...DEFAULT_NATIVE_CROSSHAIR_SETTINGS }
let writeQueue: Promise<void> = Promise.resolve()

function userDataDir(): string {
  return app.getPath('userData')
}

async function persist(): Promise<void> {
  const dest = `${userDataDir()}/${FILENAME}`
  const snapshot = settings
  const next = writeQueue.then(async () => {
    await mkdir(userDataDir(), { recursive: true })
    const tmp = `${dest}.part`
    await writeFile(tmp, JSON.stringify(snapshot, null, 2))
    await rename(tmp, dest)
  })
  writeQueue = next.catch(() => {})
  return next
}

async function loadPersisted(): Promise<void> {
  try {
    const text = await readFile(`${userDataDir()}/${FILENAME}`, 'utf-8')
    const parsed = JSON.parse(text) as Partial<NativeCrosshairSettings>
    settings = sanitizeNativeCrosshairSettings(parsed, DEFAULT_NATIVE_CROSSHAIR_SETTINGS)
  } catch {
    settings = { ...DEFAULT_NATIVE_CROSSHAIR_SETTINGS }
  }
}

/** Removes a prior instance of *this module's own* block only — content-sync's separately-marked block and the player's own lines are untouched regardless of what's found here. */
function stripOwnBlock(lines: string[]): string[] {
  const beginIndex = lines.findIndex((line) => line.trim() === BLOCK_BEGIN)
  if (beginIndex === -1) return lines
  let endIndex = lines.findIndex((line, i) => i > beginIndex && line.trim() === BLOCK_END)
  if (endIndex === -1) endIndex = lines.length - 1
  const before = lines.slice(0, beginIndex)
  const after = lines.slice(endIndex + 1)
  if (before.length > 0 && before[before.length - 1].trim() === '') before.pop()
  return [...before, ...after]
}

function buildTargetContent(existingText: string, enabled: boolean): string {
  const lines = existingText.length > 0 ? existingText.split('\n') : []
  const stripped = stripOwnBlock(lines)
  if (!enabled) {
    return stripped.join('\n')
  }
  const block = [BLOCK_BEGIN, `exec ${CFG_EXEC_NAME}`, BLOCK_END]
  const needsGap = stripped.length > 0 && stripped[stripped.length - 1].trim() !== ''
  const nextLines = needsGap ? [...stripped, '', ...block] : [...stripped, ...block]
  return `${nextLines.join('\n')}\n`
}

/**
 * Exported (not just an internal helper) so a verify script can exercise it
 * directly against a throwaway sandbox game directory, same convention as
 * content-sync.ts's syncManagedExecTargets — see CLAUDE.md's sandbox-only
 * testing rule.
 */
export async function applyNativeCrosshair(gamePath: string, s: NativeCrosshairSettings): Promise<void> {
  const cfgDestPath = resolveContentPath(gamePath, CFG_RELPATH)
  if (s.enabled) {
    await mkdir(dirname(cfgDestPath), { recursive: true })
    const tmp = `${cfgDestPath}.part`
    await writeFile(tmp, buildNativeCrosshairCfgText(s))
    await rename(tmp, cfgDestPath)
  }

  for (const targetRelPath of TARGETS) {
    const destPath = resolveContentPath(gamePath, targetRelPath)
    const existingText = await readFile(destPath, 'utf-8').catch((err) => {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return ''
      throw err
    })
    const nextText = buildTargetContent(existingText, s.enabled)
    if (nextText === existingText) continue

    await backupIfNeeded(gamePath, targetRelPath, destPath)
    await mkdir(dirname(destPath), { recursive: true })
    const tmp = `${destPath}.part`
    await writeFile(tmp, nextText)
    await rename(tmp, destPath)
  }
}

export interface NativeCrosshairStatus {
  settings: NativeCrosshairSettings
  /** False when no CS 1.6 install is currently found — settings are always saved regardless, and applied automatically the next time a game path is known (next status fetch or settings update). Settings.tsx surfaces this honestly rather than claiming success. */
  applied: boolean
}

async function tryApply(): Promise<boolean> {
  const install = await getActiveInstall()
  if (!install.installed || !install.gamePath) return false
  await applyNativeCrosshair(install.gamePath, settings)
  return true
}

export async function initNativeCrosshair(): Promise<void> {
  await loadPersisted()
}

/** Re-applies on every call (idempotent — a no-op write whenever on-disk content already matches) so status self-corrects the same way CondebugNotice/LaunchOptionsNotice do, rather than trusting a stale cached "applied" flag. */
export async function getNativeCrosshairStatus(): Promise<NativeCrosshairStatus> {
  const applied = await tryApply().catch(() => false)
  return { settings, applied }
}

export async function updateNativeCrosshairSettings(partial: Partial<NativeCrosshairSettings>): Promise<NativeCrosshairStatus> {
  settings = sanitizeNativeCrosshairSettings(partial, settings)
  await persist()
  const applied = await tryApply().catch(() => false)
  return { settings, applied }
}
